name = "ReadDatastores"
uuid = "70a005b8-9d8a-11e9-0d98-c909fa2e52d2"
authors = ["Ben J. Ward <benjward@protonmail.com>"]
version = "0.3.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"

[compat]
BioSequences = "2"
FASTX = "1.1"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
